query WUE_GetUsageExportAvailableAMIReadsTimeInterval($selectedAccount: ID, $forceLegacyData: Boolean, $first: Int, $aliased: Boolean, $nextCursor: String) { billingAccountByAuthContext(selectedAccount: $selectedAccount, forceLegacyData: $forceLegacyData) { serviceAgreementsConnection(first: $first, after: $nextCursor, onlyActive: true, aliased: $aliased) { pageInfo { hasNextPage endCursor } edges { node { uuid utilityId availableBillSegmentsInterval servicePoints { utilityId serviceType registers { availableReadsTimeInterval serviceQuantityIdentifier unitOfMeasure } } } } } } }
